### PR TITLE
Ensured that Microsoft.Bcl.Build does not affect NuProj call to GetTargetPath

### LINKED ISSUE #83: Problem with NonNuProjProjectTargetPath and Project Net4.0 with Microsoft.Async Nuget
Hello I have a problem with building .Nuproj in VS when I have a referenced project in Framework .Net4.0 and using Microsoft.Async

It's failing for this Property

<_NonNuProjProjectTargetPath>$([System.IO.Path]::GetDirectoryName($(_NonNuProjProjectTargetPath)))\</_NonNuProjProjectTargetPath>

### PR DESCRIPTION
**Pull request by PedroLamas**
`Microsoft.Bcl.Build` overrides the GetTargetPath target, so when NuProj uses that same target it does not work!

To fix this issue, we now call the target with `SkipValidatePackageReferences=true` that will bypass the `Microsoft.Bcl.Build` override

### CODE REVIEW

**Comment by PedroLamas** [comment]
This issue is still active in the latest version of NuProj. I've been patching my Nuproj.targets file manually, wonder if/when are you going to take this fix in... ;)

**Comment by AArnott** [comment]
We cannot change the set of global properties passed to the MSBuild task because that causes double-build of the referenced project. It would regress #120.

We'll need to find an alternative fix.

**Comment by PedroLamas** [comment]
Fair point, I'll try to find a different approach then!

**Comment by AArnott** [comment]
Thanks. I look forward to what you come up with.

**Comment by PedroLamas** [comment]
@AArnott I've been taking a more close look at this, and maybe I'm missing something, but I don't see it building the projects twice if I add that property... what am I missing here?

**Comment by AArnott** [comment]
Run a build at the command line with a detailed log:

    msbuild /fl /flp:verbosity=detailed

Then inspect the msbuild.log file. You should see that when the target runs that has your modified MSBuild task invocation, it will build the referenced projects a second time. You may even be able to spot that the target you invoke in that referenced project is itself executed earlier in the log file and then again by yours. 
If there is no problem with your change, you'll never see a project+target combination built twice, but instead you'll see in the log that the target was already built and thus skipped.

**Comment by PedroLamas** [comment]
I'm running a build with that command line, and I do see some tasks are re-run!

image

The diff between running with and without setting property is quite minimal (the fact you see 7 is because I have 7 projects on my solution divided by 2 packages)

I did notice something: when building from the command line I don't see the issue as when building from Visual Studio, so this change is NOT needed when building from the command line!

So I would suggest to detect when a Visual Studio build is running and only then adding it!

Granted this is not the best solution, but at this point I still don't see a big impact in adding this property (at least by comparing the two builds output)

**Pull request closed without merging**
