### PR TITLE
Nuproj.Common package for non-NuProj projects

### PR DESCRIPTION
**Pull request by kovalikp**
Package that provides _NuProjProjectReferenceClosure target.

### CODE REVIEW

**Comment by AArnott** [comment]
This LGTM. @terrajobst what do you think?

@kovalikp how does this new .nuproj get built? I don't see any change to wire it up to the overall build or add it to the solution.

**Comment by kovalikp** [comment]
Well, this is just quick and dirty solution for our problem.
With this, user will have to install NuProj as a solution package, and NuProj.Common to the .csproj dependencies (should probably mention this in docs).

To use `build\NuProj.props` and `build\NuProj.targets` for .nuproj projects as suggested earlier, we would have to add `CPS;AssemblyReferences;DeclaredSourceItem;UserSourceItems` capabilities.
At least according to this https://github.com/NuGet/NuGet.VisualStudioExtension/pull/30. But `AssemblyReference` capability is not applicable in our case.

Ideally NuGet would support atomic capabilities for AddFile, AddReference, AddFrameworkReference, AddImport and so on. Or even better, have a capability to somehow get implementation of `IMSBuildNuGetProjectSystem` from CPS project. Maybe I should put this into coherent proposal and raise an issue in NuGet project.

**Comment by AArnott** [comment]
I'm in close contact with the NuGet folks to break up their bulk check for these several capabilities to allow for `AssemblyReferences` at least to be missing. I haven't heard a commitment to support for RTM yet, but they do want to add support for it to support other CPS-based projects too.
I agree we should *not* advertise such support in nuproj inappropriately.

**Comment by kovalikp** [comment]
@AArnott @terrajobst are you going to merge this?

**Comment by AArnott** [comment]
I like it, yes. But my earlier question remains: 

> how does this new .nuproj get built? I don't see any change to wire it up to the overall build or add it to the solution.

I'd like to see this wired up so that it builds the new nupkg with the rest of the code so we can build and publish it altogether. Or do you have something else in mind?

**Comment by kovalikp** [comment]
Ah, sorry. I thought you were asking about how users' .nuproj files get build. 

`package.proj` file picks up all .nuproj files from `src\NuProj.Packages` directory. See here: https://github.com/nuproj/nuproj/blob/master/tools/package.proj#L39

**Comment by AArnott** [comment]
OK. I wasn't expecting a wildcard. cool.
I'll try out these changes locally and merge if all looks good.

**Pull request merged**
