### PR TITLE
Support inferring the value for $(Version) from the project being packaged 

### PR DESCRIPTION
**Pull request by williamb1024**
Fixes issue #20

### CODE REVIEW

**Comment by williamb1024** [comment]
Adds support for reading attributes from referenced project output. Similar to what is described in #20, with a few differences.

Reads the following assembly attributes:
AssemblyName (not an attribute, but included anyway)
AssemblyVersion
AssemblyFileVersion
AssemblyTitle
AssemblyCompany
AssemblyDescription
AssemblyCopyright
AssemblyCulture
AssemblyConfiguration
AssemblyTrademark
AssemblyProduct
AssemblyMetadata (as many as defined)

AssemblyVersion and AssemblyFileVersion are also split into: xxx_Major, xxx_Minor, xxx_Build, xxx_Revision

AssemblyMetadata attributes are referenced by their associated name. For example:
[assembly: AssemblyMetadata("ProjectUrl", "SomeUrl")] would be referenced as "ProjectUrl".

In order to support multiple project references, all attributes are prefixed as follows:

[ProjectFileName]_[attributename]
[ProjectFileName].[ext]_[attributename]
[ProjectFileName].[targetFramework]_[attributename]
[ProjectFileName].[ext].[targetFramework]_[attributename]

A referenced project named "ClassLibray1.csproj" targeting 4.5 would create the following prefixes:
ClassLibrary1_AssemblyVersion
ClassLibrary1.csproj_AssemblyVersion
ClassLibrary1.net45_AssemblyVersion
ClassLibrary1.csproj.net45_AssemblyVersion

The tasks do not create MSBuild properties for each attribute, because I couldn't think of a way to re-evaluate the properties after the project references had been determined. Rather, a known list of properties (defined in NuSpecProjectProperties ItemGroup) are used to determine which properties should be "expanded". 

Expansion replaces instances of "|attributename|" with the value defined by the associated assembly. Two pipe characters may be used as an escape to produce a single pipe character. I choose the pipe character because it will not conflict (at least on Windows) with a project file name.

**Comment by vercellone** [comment]
What is holding up this merge?  Is it a matter of dependencies for a build server deployment scenario?

**Comment by mbogbp** [comment]
Any idea when this will be be merged?

**Comment by AArnott** [comment]
We should reconcile this change with #76

**Comment by AArnott** [comment]
@williamb1024 After #76 is merged in, can you please update your pull request as necessary to avoid merge conflicts and fit into what it does?

**Comment by williamb1024** [comment]
@AArnott I'll take a look at #76 changes and see how the two fit together.

**Comment by williamb1024** [comment]
I see that #76 has been merged, I'll get this PR updated shortly.

**Comment by williamb1024** [comment]
@AArnott I've dealt with the merge conflicts, but unfortunately I've broken a number of the tests because of the problem with the Clean targets (Issue #59). A number of the tests use the "Rebuild" target, which depends on property expansion and ultimately building project references. The project references are built then deleted, but since the build targets have already been run they aren't run again as part of the "Build" target. Or at least, I believe that is what is happening.

So, I'm stuck at the moment, as I can't complete this PR until something can be done about implementing the "Clean" target in a manner that doesn't rely on revaluation of project references to determine the appropriate files to delete during cleaning.

Suggestions for proceeding?

**Comment by kovalikp** [comment]
During the build, you could write list of all produced files into `$(IntermmediateOutputPath)$(MSBuildProjectFile).FileListAbsolute.txt` file. `Clean` target would then delete anything listed there, including that file. You can have look at `CoreClean` target in `Microsoft.Common.CurrentVersion.targets` for inspiration. ;)

**Comment by williamb1024** [comment]
@kovalikp That's what PR #66 does, but in the comments for #59 terajobst indicates that he has issues with that solution.

**Comment by kovalikp** [comment]
Completely forgot about that one. I need to wake up :blush:

**Comment by AArnott** [comment]
Merge conflicts, and NuProj is reaching end of life so we're not taking new features. See #282

**Pull request closed without merging**
