### PR TITLE
Added missing NuGet package.

### PR DESCRIPTION
**Pull request by kovalikp**
Added Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime package.

### CODE REVIEW

**Comment by AArnott** [comment]
Why do you say this is missing? It wasn't there before. Why does it need to be there now?

**Comment by kovalikp** [comment]
I've installed VS 2015 and SDK, and then tried to build Dev14 project. The reference for that assembly was missing, so I had to install the package.

**Comment by kovalikp** [comment]
Ok, so it appears I can build the solution now - maybe I was indeed missing VS SDK or something. Though it's weird every assembly is being loaded from NuGet, except for `Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime` which is being loaded from GAC.

I think we should be consistent in this case and not make exceptions.

**Comment by AArnott** [comment]
Yes, I suspect you hadn't installed the VS SDK. We have a lot of references to VS assemblies and your pull request only converts _one_ of them to use NuGet. That seems to leave us in an inconsistent state. Are you interested in enhancing this by switching all the references to NuGet packages for which packages are available?

**Comment by kovalikp** [comment]
It's one of the errors that causes AppVeyor build to fail. There are couple more errors there, though it will probably require @terrajobst to change AppVeyor setting to use VS 2015. Dunno how is the current environment configured.

**Comment by kovalikp** [comment]
I'll create new PR with updated packages.

**Pull request closed without merging**
